[package]
name = "ams-tls"
description = "TLS 1.3 : établissement et chiffrement d'enregistrements, sans entrée-sortie"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]


[lints]
workspace = true
