[package]
name = "ams-config"
description = "Schéma Cap'n Proto de la configuration, lecture et écriture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
ams-guard = { workspace = true }
ams-proto-smtp = { workspace = true }
capnp = { workspace = true }


[lints]
workspace = true
