// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! La table statique de QPACK, **ENGENDRÉE** depuis RFC 9204 Appendice A.
//!
//! # ELLE N'A RIEN À VOIR AVEC CELLE DE HPACK, ET C'EST VOULU
//!
//! HPACK avait soixante et une entrées, choisies en 2013. Celle-ci en a
//! quatre-vingt-dix-neuf, « generated by analyzing actual Internet traffic in
//! 2018 » : les valeurs de `content-security-policy`, les méthodes CORS, les
//! types de `content-type` les plus vus. **L'ordre lui-même est optimisé** pour
//! que les champs les plus fréquents portent les plus petits index.
//!
//! Les deux tables se ressemblent assez pour qu'on les confonde, et diffèrent
//! assez pour que la confusion soit indétectable : un index qui désigne
//! `:method GET` dans l'une désigne autre chose dans l'autre, et le message
//! décodé serait faux sans qu'aucune faute ne se voie. C'est pourquoi cette
//! table est ENGENDRÉE depuis la RFC, et non recopiée à la main.
//!
//! # LES ENTRÉES SE RÉPÈTENT, ET CE N'EST PAS UNE ERREUR
//!
//! L'appendice le dit : « some of the entries may be inconsistent or appear
//! multiple times with similar but not identical values ». `content-type`
//! apparaît dix-neuf fois, `:status` vingt-deux fois. Un décodeur qui
//! s'attendrait à des noms uniques se tromperait.

/// Combien d'entrées la table statique porte (§3.1).
///
/// En `usize` : c'est une longueur de tranche. La comparaison avec un index venu
/// du fil, qui est un `u64`, se fait par `get` — et non par une conversion qu'il
/// faudrait refuser.
pub const STATIQUE_LEN: usize = 99;

/// La table statique, telle que l'appendice A la donne.
pub const STATIQUE: [(&[u8], &[u8]); STATIQUE_LEN] = [
    (b":authority", b""),
    (b":path", b"/"),
    (b"age", b"0"),
    (b"content-disposition", b""),
    (b"content-length", b"0"),
    (b"cookie", b""),
    (b"date", b""),
    (b"etag", b""),
    (b"if-modified-since", b""),
    (b"if-none-match", b""),
    (b"last-modified", b""),
    (b"link", b""),
    (b"location", b""),
    (b"referer", b""),
    (b"set-cookie", b""),
    (b":method", b"CONNECT"),
    (b":method", b"DELETE"),
    (b":method", b"GET"),
    (b":method", b"HEAD"),
    (b":method", b"OPTIONS"),
    (b":method", b"POST"),
    (b":method", b"PUT"),
    (b":scheme", b"http"),
    (b":scheme", b"https"),
    (b":status", b"103"),
    (b":status", b"200"),
    (b":status", b"304"),
    (b":status", b"404"),
    (b":status", b"503"),
    (b"accept", b"*/*"),
    (b"accept", b"application/dns-message"),
    (b"accept-encoding", b"gzip, deflate, br"),
    (b"accept-ranges", b"bytes"),
    (b"access-control-allow-headers", b"cache-control"),
    (b"access-control-allow-headers", b"content-type"),
    (b"access-control-allow-origin", b"*"),
    (b"cache-control", b"max-age=0"),
    (b"cache-control", b"max-age=2592000"),
    (b"cache-control", b"max-age=604800"),
    (b"cache-control", b"no-cache"),
    (b"cache-control", b"no-store"),
    (b"cache-control", b"public, max-age=31536000"),
    (b"content-encoding", b"br"),
    (b"content-encoding", b"gzip"),
    (b"content-type", b"application/dns-message"),
    (b"content-type", b"application/javascript"),
    (b"content-type", b"application/json"),
    (b"content-type", b"application/x-www-form-urlencoded"),
    (b"content-type", b"image/gif"),
    (b"content-type", b"image/jpeg"),
    (b"content-type", b"image/png"),
    (b"content-type", b"text/css"),
    (b"content-type", b"text/html; charset=utf-8"),
    (b"content-type", b"text/plain"),
    (b"content-type", b"text/plain;charset=utf-8"),
    (b"range", b"bytes=0-"),
    (b"strict-transport-security", b"max-age=31536000"),
    (
        b"strict-transport-security",
        b"max-age=31536000; includesubdomains",
    ),
    (
        b"strict-transport-security",
        b"max-age=31536000; includesubdomains; preload",
    ),
    (b"vary", b"accept-encoding"),
    (b"vary", b"origin"),
    (b"x-content-type-options", b"nosniff"),
    (b"x-xss-protection", b"1; mode=block"),
    (b":status", b"100"),
    (b":status", b"204"),
    (b":status", b"206"),
    (b":status", b"302"),
    (b":status", b"400"),
    (b":status", b"403"),
    (b":status", b"421"),
    (b":status", b"425"),
    (b":status", b"500"),
    (b"accept-language", b""),
    (b"access-control-allow-credentials", b"FALSE"),
    (b"access-control-allow-credentials", b"TRUE"),
    (b"access-control-allow-headers", b"*"),
    (b"access-control-allow-methods", b"get"),
    (b"access-control-allow-methods", b"get, post, options"),
    (b"access-control-allow-methods", b"options"),
    (b"access-control-expose-headers", b"content-length"),
    (b"access-control-request-headers", b"content-type"),
    (b"access-control-request-method", b"get"),
    (b"access-control-request-method", b"post"),
    (b"alt-svc", b"clear"),
    (b"authorization", b""),
    (
        b"content-security-policy",
        b"script-src 'none'; object-src 'none'; base-uri 'none'",
    ),
    (b"early-data", b"1"),
    (b"expect-ct", b""),
    (b"forwarded", b""),
    (b"if-range", b""),
    (b"origin", b""),
    (b"purpose", b"prefetch"),
    (b"server", b""),
    (b"timing-allow-origin", b"*"),
    (b"upgrade-insecure-requests", b"1"),
    (b"user-agent", b""),
    (b"x-forwarded-for", b""),
    (b"x-frame-options", b"deny"),
    (b"x-frame-options", b"sameorigin"),
];

/// L'entrée d'un index de la table statique.
///
/// # ELLE COMMENCE À ZÉRO, ET CELLE DE HPACK COMMENÇAIT À UN
///
/// §3.1 : « the static table […] is indexed starting at zero ». HPACK réservait
/// le zéro pour dire « rien », et sa première entrée portait l'index un. Un
/// décodeur qui garderait l'habitude de HPACK décalerait toute la table d'un
/// rang — et lirait `:path` là où le pair a écrit `:authority`.
#[must_use]
pub fn entree_statique(index: u64) -> Option<(&'static [u8], &'static [u8])> {
    // Un index venu du fil est un `u64` ; la table est indexée par un `usize`.
    // `usize::MAX` fait manquer le `get` à coup sûr, là où un `try_from` fautif
    // ouvrirait une branche qu'aucune cible de soixante-quatre bits ne peut
    // emprunter.
    let rang = usize::try_from(index).unwrap_or(usize::MAX);
    STATIQUE.get(rang).copied()
}

#[cfg(test)]
mod tests;
