[package]
name = "ams-rt-std"
description = "Implémentation des traits d'ams-rt sur la bibliothèque standard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
ams-rt = { workspace = true }

[lints]
workspace = true
